sudo: required
services:
  - docker

before_install:
  - docker build -t williamszk/docker-react-udemy-grider-2 -f Dockerfile.dev .

script:
  - docker run -e CI=true williamszk/docker-react-udemy-grider-2 npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'delete-me-application-test'
  env: 'Delete-me-application-test-env-3'
  bucket_name: 'elasticbeanstalk-us-east-1-770482222490'
  bucket_path: 'delete-me-application-test'
  on:
    branch: main
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
