sudo: required
services:
  - docker

before_install:
  - docker build -t williamszk/docker-react-udemy-grider-2 -f Dockerfile.dev .

script:
  - docker run -e CI=true williamszk/docker-react-udemy-grider-2 npm run test
